format:
  line_width: 80
  tab_size: 2
  use_tabchars: false
  fractional_tab_policy: use-space
  max_subgroups_hwrap: 1
  max_pargs_hwrap: 6
  max_rows_cmdline: 3
  dangle_align: prefix-indent
  command_case: lower
  keyword_case: uppper
  _help_enable_sort:
  - If true, the argument lists which are known to be sortable
  - will be sorted lexicographicall
  enable_sort: true
  _help_autosort:
  - If true, the parsers may infer whether or not an argument
  - list is sortable (without annotation).
  autosort: false
